window.esdocSearchIndex = [
  [
    "./js/object.js~abstracthierarchy",
    "class/js/object.js~AbstractHierarchy.html",
    "<span>AbstractHierarchy</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~char",
    "class/js/object.js~Char.html",
    "<span>Char</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~commandline",
    "class/js/object.js~CommandLine.html",
    "<span>CommandLine</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~convertcontainer",
    "class/js/object.js~ConvertContainer.html",
    "<span>ConvertContainer</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~convertview",
    "class/js/object.js~ConvertView.html",
    "<span>ConvertView</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~cursor",
    "class/js/object.js~Cursor.html",
    "<span>Cursor</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~directory",
    "class/js/object.js~Directory.html",
    "<span>Directory</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~eol",
    "class/js/object.js~EOL.html",
    "<span>EOL</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~file",
    "class/js/object.js~File.html",
    "<span>File</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~filelist",
    "class/js/object.js~FileList.html",
    "<span>FileList</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~inputbuffer",
    "class/js/object.js~InputBuffer.html",
    "<span>InputBuffer</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~inputchar",
    "class/js/object.js~InputChar.html",
    "<span>InputChar</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~menu",
    "class/js/object.js~Menu.html",
    "<span>Menu</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~paragraph",
    "class/js/object.js~Paragraph.html",
    "<span>Paragraph</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~row",
    "class/js/object.js~Row.html",
    "<span>Row</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~sentencecontainer",
    "class/js/object.js~SentenceContainer.html",
    "<span>SentenceContainer</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "class"
  ],
  [
    "./js/object.js~util",
    "variable/index.html#static-variable-Util",
    "<span>Util</span> <span class=\"search-result-import-path\">./js/object.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "js/key_table.js",
    "file/js/key_table.js.html",
    "js/key_table.js",
    "file"
  ],
  [
    "js/object.js",
    "file/js/object.js.html",
    "js/object.js",
    "file"
  ],
  [
    "js/object.js~abstracthierarchy#addclass",
    "class/js/object.js~AbstractHierarchy.html#instance-method-addClass",
    "js/object.js~AbstractHierarchy#addClass",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#addclickeventlistener",
    "class/js/object.js~AbstractHierarchy.html#instance-method-addClickEventListener",
    "js/object.js~AbstractHierarchy#addClickEventListener",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#addkeydowneventlistener",
    "class/js/object.js~AbstractHierarchy.html#instance-method-addKeydownEventListener",
    "js/object.js~AbstractHierarchy#addKeydownEventListener",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#addwheeleventlistener",
    "class/js/object.js~AbstractHierarchy.html#instance-method-addWheelEventListener",
    "js/object.js~AbstractHierarchy#addWheelEventListener",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#childlength",
    "class/js/object.js~AbstractHierarchy.html#instance-method-childLength",
    "js/object.js~AbstractHierarchy#childLength",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#children",
    "class/js/object.js~AbstractHierarchy.html#instance-method-children",
    "js/object.js~AbstractHierarchy#children",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#classname",
    "class/js/object.js~AbstractHierarchy.html#instance-method-className",
    "js/object.js~AbstractHierarchy#className",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#computecenterpoint",
    "class/js/object.js~AbstractHierarchy.html#instance-method-computeCenterPoint",
    "js/object.js~AbstractHierarchy#computeCenterPoint",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#computedistancefrompoint",
    "class/js/object.js~AbstractHierarchy.html#instance-method-computeDistanceFromPoint",
    "js/object.js~AbstractHierarchy#computeDistanceFromPoint",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#constructor",
    "class/js/object.js~AbstractHierarchy.html#instance-constructor-constructor",
    "js/object.js~AbstractHierarchy#constructor",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#deletechild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-deleteChild",
    "js/object.js~AbstractHierarchy#deleteChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#elem",
    "class/js/object.js~AbstractHierarchy.html#instance-method-elem",
    "js/object.js~AbstractHierarchy#elem",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#empty",
    "class/js/object.js~AbstractHierarchy.html#instance-method-empty",
    "js/object.js~AbstractHierarchy#empty",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#emptychild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-emptyChild",
    "js/object.js~AbstractHierarchy#emptyChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#emptyelem",
    "class/js/object.js~AbstractHierarchy.html#instance-method-emptyElem",
    "js/object.js~AbstractHierarchy#emptyElem",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#firstchild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-firstChild",
    "js/object.js~AbstractHierarchy#firstChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#haschild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-hasChild",
    "js/object.js~AbstractHierarchy#hasChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#hasclass",
    "class/js/object.js~AbstractHierarchy.html#instance-method-hasClass",
    "js/object.js~AbstractHierarchy#hasClass",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#hasnextsibling",
    "class/js/object.js~AbstractHierarchy.html#instance-method-hasNextSibling",
    "js/object.js~AbstractHierarchy#hasNextSibling",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#hasprevsibling",
    "class/js/object.js~AbstractHierarchy.html#instance-method-hasPrevSibling",
    "js/object.js~AbstractHierarchy#hasPrevSibling",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#height",
    "class/js/object.js~AbstractHierarchy.html#instance-method-height",
    "js/object.js~AbstractHierarchy#height",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#index",
    "class/js/object.js~AbstractHierarchy.html#instance-method-index",
    "js/object.js~AbstractHierarchy#index",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#insertchild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-insertChild",
    "js/object.js~AbstractHierarchy#insertChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#is",
    "class/js/object.js~AbstractHierarchy.html#instance-method-is",
    "js/object.js~AbstractHierarchy#is",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#isempty",
    "class/js/object.js~AbstractHierarchy.html#instance-method-isEmpty",
    "js/object.js~AbstractHierarchy#isEmpty",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#isfirst",
    "class/js/object.js~AbstractHierarchy.html#instance-method-isFirst",
    "js/object.js~AbstractHierarchy#isFirst",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#islast",
    "class/js/object.js~AbstractHierarchy.html#instance-method-isLast",
    "js/object.js~AbstractHierarchy#isLast",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#isonlychild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-isOnlyChild",
    "js/object.js~AbstractHierarchy#isOnlyChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#lastchild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-lastChild",
    "js/object.js~AbstractHierarchy#lastChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#length",
    "class/js/object.js~AbstractHierarchy.html#instance-method-length",
    "js/object.js~AbstractHierarchy#length",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#next",
    "class/js/object.js~AbstractHierarchy.html#instance-method-next",
    "js/object.js~AbstractHierarchy#next",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#parent",
    "class/js/object.js~AbstractHierarchy.html#instance-method-parent",
    "js/object.js~AbstractHierarchy#parent",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#prev",
    "class/js/object.js~AbstractHierarchy.html#instance-method-prev",
    "js/object.js~AbstractHierarchy#prev",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#pushchild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-pushChild",
    "js/object.js~AbstractHierarchy#pushChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#removeclass",
    "class/js/object.js~AbstractHierarchy.html#instance-method-removeClass",
    "js/object.js~AbstractHierarchy#removeClass",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#removeclassfromallchild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-removeClassFromAllChild",
    "js/object.js~AbstractHierarchy#removeClassFromAllChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#removeclickeventlistener",
    "class/js/object.js~AbstractHierarchy.html#instance-method-removeClickEventListener",
    "js/object.js~AbstractHierarchy#removeClickEventListener",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#removekeydowneventlistener",
    "class/js/object.js~AbstractHierarchy.html#instance-method-removeKeydownEventListener",
    "js/object.js~AbstractHierarchy#removeKeydownEventListener",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#removewheeleventlistener",
    "class/js/object.js~AbstractHierarchy.html#instance-method-removeWheelEventListener",
    "js/object.js~AbstractHierarchy#removeWheelEventListener",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#replacechild",
    "class/js/object.js~AbstractHierarchy.html#instance-method-replaceChild",
    "js/object.js~AbstractHierarchy#replaceChild",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#text",
    "class/js/object.js~AbstractHierarchy.html#instance-method-text",
    "js/object.js~AbstractHierarchy#text",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#width",
    "class/js/object.js~AbstractHierarchy.html#instance-method-width",
    "js/object.js~AbstractHierarchy#width",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#x",
    "class/js/object.js~AbstractHierarchy.html#instance-method-x",
    "js/object.js~AbstractHierarchy#x",
    "method"
  ],
  [
    "js/object.js~abstracthierarchy#y",
    "class/js/object.js~AbstractHierarchy.html#instance-method-y",
    "js/object.js~AbstractHierarchy#y",
    "method"
  ],
  [
    "js/object.js~char#addcursor",
    "class/js/object.js~Char.html#instance-method-addCursor",
    "js/object.js~Char#addCursor",
    "method"
  ],
  [
    "js/object.js~char#after",
    "class/js/object.js~Char.html#instance-method-after",
    "js/object.js~Char#after",
    "method"
  ],
  [
    "js/object.js~char#aftereach",
    "class/js/object.js~Char.html#instance-method-afterEach",
    "js/object.js~Char#afterEach",
    "method"
  ],
  [
    "js/object.js~char#before",
    "class/js/object.js~Char.html#instance-method-before",
    "js/object.js~Char#before",
    "method"
  ],
  [
    "js/object.js~char#bold",
    "class/js/object.js~Char.html#instance-method-bold",
    "js/object.js~Char#bold",
    "method"
  ],
  [
    "js/object.js~char#color",
    "class/js/object.js~Char.html#instance-method-color",
    "js/object.js~Char#color",
    "method"
  ],
  [
    "js/object.js~char#constructor",
    "class/js/object.js~Char.html#instance-constructor-constructor",
    "js/object.js~Char#constructor",
    "method"
  ],
  [
    "js/object.js~char#createdata",
    "class/js/object.js~Char.html#instance-method-createData",
    "js/object.js~Char#createData",
    "method"
  ],
  [
    "js/object.js~char#cursor",
    "class/js/object.js~Char.html#instance-method-cursor",
    "js/object.js~Char#cursor",
    "method"
  ],
  [
    "js/object.js~char#data",
    "class/js/object.js~Char.html#instance-method-data",
    "js/object.js~Char#data",
    "method"
  ],
  [
    "js/object.js~char#delete",
    "class/js/object.js~Char.html#instance-method-delete",
    "js/object.js~Char#delete",
    "method"
  ],
  [
    "js/object.js~char#display",
    "class/js/object.js~Char.html#instance-method-display",
    "js/object.js~Char#display",
    "method"
  ],
  [
    "js/object.js~char#fontsize",
    "class/js/object.js~Char.html#instance-method-fontSize",
    "js/object.js~Char#fontSize",
    "method"
  ],
  [
    "js/object.js~char#hascursor",
    "class/js/object.js~Char.html#instance-method-hasCursor",
    "js/object.js~Char#hasCursor",
    "method"
  ],
  [
    "js/object.js~char#hasnextcharonparagraph",
    "class/js/object.js~Char.html#instance-method-hasNextCharOnParagraph",
    "js/object.js~Char#hasNextCharOnParagraph",
    "method"
  ],
  [
    "js/object.js~char#hasnextsibling",
    "class/js/object.js~Char.html#instance-method-hasNextSibling",
    "js/object.js~Char#hasNextSibling",
    "method"
  ],
  [
    "js/object.js~char#hasprevcharonparagraph",
    "class/js/object.js~Char.html#instance-method-hasPrevCharOnParagraph",
    "js/object.js~Char#hasPrevCharOnParagraph",
    "method"
  ],
  [
    "js/object.js~char#isbold",
    "class/js/object.js~Char.html#instance-method-isBold",
    "js/object.js~Char#isBold",
    "method"
  ],
  [
    "js/object.js~char#isdisplay",
    "class/js/object.js~Char.html#instance-method-isDisplay",
    "js/object.js~Char#isDisplay",
    "method"
  ],
  [
    "js/object.js~char#iseol",
    "class/js/object.js~Char.html#instance-method-isEOL",
    "js/object.js~Char#isEOL",
    "method"
  ],
  [
    "js/object.js~char#isinrange",
    "class/js/object.js~Char.html#instance-method-isInRange",
    "js/object.js~Char#isInRange",
    "method"
  ],
  [
    "js/object.js~char#isitalic",
    "class/js/object.js~Char.html#instance-method-isItalic",
    "js/object.js~Char#isItalic",
    "method"
  ],
  [
    "js/object.js~char#italic",
    "class/js/object.js~Char.html#instance-method-italic",
    "js/object.js~Char#italic",
    "method"
  ],
  [
    "js/object.js~char#marksearchphrase",
    "class/js/object.js~Char.html#instance-method-markSearchPhrase",
    "js/object.js~Char#markSearchPhrase",
    "method"
  ],
  [
    "js/object.js~char#movefirstafter",
    "class/js/object.js~Char.html#instance-method-moveFirstAfter",
    "js/object.js~Char#moveFirstAfter",
    "method"
  ],
  [
    "js/object.js~char#movelastbefore",
    "class/js/object.js~Char.html#instance-method-moveLastBefore",
    "js/object.js~Char#moveLastBefore",
    "method"
  ],
  [
    "js/object.js~char#nextchar",
    "class/js/object.js~Char.html#instance-method-nextChar",
    "js/object.js~Char#nextChar",
    "method"
  ],
  [
    "js/object.js~char#nextcharonparagraph",
    "class/js/object.js~Char.html#instance-method-nextCharOnParagraph",
    "js/object.js~Char#nextCharOnParagraph",
    "method"
  ],
  [
    "js/object.js~char#paragraph",
    "class/js/object.js~Char.html#instance-method-paragraph",
    "js/object.js~Char#paragraph",
    "method"
  ],
  [
    "js/object.js~char#prevchar",
    "class/js/object.js~Char.html#instance-method-prevChar",
    "js/object.js~Char#prevChar",
    "method"
  ],
  [
    "js/object.js~char#prevcharonparagraph",
    "class/js/object.js~Char.html#instance-method-prevCharOnParagraph",
    "js/object.js~Char#prevCharOnParagraph",
    "method"
  ],
  [
    "js/object.js~char#remove",
    "class/js/object.js~Char.html#instance-method-remove",
    "js/object.js~Char#remove",
    "method"
  ],
  [
    "js/object.js~char#replace",
    "class/js/object.js~Char.html#instance-method-replace",
    "js/object.js~Char#replace",
    "method"
  ],
  [
    "js/object.js~char#row",
    "class/js/object.js~Char.html#instance-method-row",
    "js/object.js~Char#row",
    "method"
  ],
  [
    "js/object.js~char#sentencecontainer",
    "class/js/object.js~Char.html#instance-method-sentenceContainer",
    "js/object.js~Char#sentenceContainer",
    "method"
  ],
  [
    "js/object.js~char#setposmemory",
    "class/js/object.js~Char.html#instance-method-setPosMemory",
    "js/object.js~Char#setPosMemory",
    "method"
  ],
  [
    "js/object.js~char#slidenextcursor",
    "class/js/object.js~Char.html#instance-method-slideNextCursor",
    "js/object.js~Char#slideNextCursor",
    "method"
  ],
  [
    "js/object.js~char#slideprevcursor",
    "class/js/object.js~Char.html#instance-method-slidePrevCursor",
    "js/object.js~Char#slidePrevCursor",
    "method"
  ],
  [
    "js/object.js~char.createplainchardata",
    "class/js/object.js~Char.html#static-method-createPlainCharData",
    "js/object.js~Char.createPlainCharData",
    "method"
  ],
  [
    "js/object.js~commandline#active",
    "class/js/object.js~CommandLine.html#instance-method-active",
    "js/object.js~CommandLine#active",
    "method"
  ],
  [
    "js/object.js~commandline#addfocusouteventlistener",
    "class/js/object.js~CommandLine.html#instance-method-addFocusoutEventListener",
    "js/object.js~CommandLine#addFocusoutEventListener",
    "method"
  ],
  [
    "js/object.js~commandline#addkeyupeventlistener",
    "class/js/object.js~CommandLine.html#instance-method-addKeyupEventListener",
    "js/object.js~CommandLine#addKeyupEventListener",
    "method"
  ],
  [
    "js/object.js~commandline#constructor",
    "class/js/object.js~CommandLine.html#instance-constructor-constructor",
    "js/object.js~CommandLine#constructor",
    "method"
  ],
  [
    "js/object.js~commandline#displayfilemodal",
    "class/js/object.js~CommandLine.html#instance-method-displayFileModal",
    "js/object.js~CommandLine#displayFileModal",
    "method"
  ],
  [
    "js/object.js~commandline#elem",
    "class/js/object.js~CommandLine.html#instance-method-elem",
    "js/object.js~CommandLine#elem",
    "method"
  ],
  [
    "js/object.js~commandline#filelist",
    "class/js/object.js~CommandLine.html#instance-method-fileList",
    "js/object.js~CommandLine#fileList",
    "method"
  ],
  [
    "js/object.js~commandline#focus",
    "class/js/object.js~CommandLine.html#instance-method-focus",
    "js/object.js~CommandLine#focus",
    "method"
  ],
  [
    "js/object.js~commandline#hidefilemodal",
    "class/js/object.js~CommandLine.html#instance-method-hideFileModal",
    "js/object.js~CommandLine#hideFileModal",
    "method"
  ],
  [
    "js/object.js~commandline#isactive",
    "class/js/object.js~CommandLine.html#instance-method-isActive",
    "js/object.js~CommandLine#isActive",
    "method"
  ],
  [
    "js/object.js~commandline#onfocusout",
    "class/js/object.js~CommandLine.html#instance-method-onFocusout",
    "js/object.js~CommandLine#onFocusout",
    "method"
  ],
  [
    "js/object.js~commandline#removefocusouteventlistener",
    "class/js/object.js~CommandLine.html#instance-method-removeFocusoutEventListener",
    "js/object.js~CommandLine#removeFocusoutEventListener",
    "method"
  ],
  [
    "js/object.js~commandline#removekeyupeventlistener",
    "class/js/object.js~CommandLine.html#instance-method-removeKeyupEventListener",
    "js/object.js~CommandLine#removeKeyupEventListener",
    "method"
  ],
  [
    "js/object.js~commandline#runcommand",
    "class/js/object.js~CommandLine.html#instance-method-runCommand",
    "js/object.js~CommandLine#runCommand",
    "method"
  ],
  [
    "js/object.js~commandline#runkeyup",
    "class/js/object.js~CommandLine.html#instance-method-runKeyup",
    "js/object.js~CommandLine#runKeyup",
    "method"
  ],
  [
    "js/object.js~commandline#sentencecontainer",
    "class/js/object.js~CommandLine.html#instance-method-sentenceContainer",
    "js/object.js~CommandLine#sentenceContainer",
    "method"
  ],
  [
    "js/object.js~commandline#start",
    "class/js/object.js~CommandLine.html#instance-method-start",
    "js/object.js~CommandLine#start",
    "method"
  ],
  [
    "js/object.js~commandline#stop",
    "class/js/object.js~CommandLine.html#instance-method-stop",
    "js/object.js~CommandLine#stop",
    "method"
  ],
  [
    "js/object.js~commandline#unactive",
    "class/js/object.js~CommandLine.html#instance-method-unActive",
    "js/object.js~CommandLine#unActive",
    "method"
  ],
  [
    "js/object.js~commandline#val",
    "class/js/object.js~CommandLine.html#instance-method-val",
    "js/object.js~CommandLine#val",
    "method"
  ],
  [
    "js/object.js~convertcontainer#activeview",
    "class/js/object.js~ConvertContainer.html#instance-method-activeView",
    "js/object.js~ConvertContainer#activeView",
    "method"
  ],
  [
    "js/object.js~convertcontainer#addkeydowneventlistener",
    "class/js/object.js~ConvertContainer.html#instance-method-addKeydownEventListener",
    "js/object.js~ConvertContainer#addKeydownEventListener",
    "method"
  ],
  [
    "js/object.js~convertcontainer#append",
    "class/js/object.js~ConvertContainer.html#instance-method-append",
    "js/object.js~ConvertContainer#append",
    "method"
  ],
  [
    "js/object.js~convertcontainer#backspace",
    "class/js/object.js~ConvertContainer.html#instance-method-backSpace",
    "js/object.js~ConvertContainer#backSpace",
    "method"
  ],
  [
    "js/object.js~convertcontainer#constructor",
    "class/js/object.js~ConvertContainer.html#instance-constructor-constructor",
    "js/object.js~ConvertContainer#constructor",
    "method"
  ],
  [
    "js/object.js~convertcontainer#convert",
    "class/js/object.js~ConvertContainer.html#instance-method-convert",
    "js/object.js~ConvertContainer#convert",
    "method"
  ],
  [
    "js/object.js~convertcontainer#createviews",
    "class/js/object.js~ConvertContainer.html#instance-method-createViews",
    "js/object.js~ConvertContainer#createViews",
    "method"
  ],
  [
    "js/object.js~convertcontainer#cursorx",
    "class/js/object.js~ConvertContainer.html#instance-method-cursorX",
    "js/object.js~ConvertContainer#cursorX",
    "method"
  ],
  [
    "js/object.js~convertcontainer#cursory",
    "class/js/object.js~ConvertContainer.html#instance-method-cursorY",
    "js/object.js~ConvertContainer#cursorY",
    "method"
  ],
  [
    "js/object.js~convertcontainer#hide",
    "class/js/object.js~ConvertContainer.html#instance-method-hide",
    "js/object.js~ConvertContainer#hide",
    "method"
  ],
  [
    "js/object.js~convertcontainer#inputbuffer",
    "class/js/object.js~ConvertContainer.html#instance-method-inputBuffer",
    "js/object.js~ConvertContainer#inputBuffer",
    "method"
  ],
  [
    "js/object.js~convertcontainer#isactive",
    "class/js/object.js~ConvertContainer.html#instance-method-isActive",
    "js/object.js~ConvertContainer#isActive",
    "method"
  ],
  [
    "js/object.js~convertcontainer#print",
    "class/js/object.js~ConvertContainer.html#instance-method-print",
    "js/object.js~ConvertContainer#print",
    "method"
  ],
  [
    "js/object.js~convertcontainer#replace",
    "class/js/object.js~ConvertContainer.html#instance-method-replace",
    "js/object.js~ConvertContainer#replace",
    "method"
  ],
  [
    "js/object.js~convertcontainer#reposition",
    "class/js/object.js~ConvertContainer.html#instance-method-reposition",
    "js/object.js~ConvertContainer#reposition",
    "method"
  ],
  [
    "js/object.js~convertcontainer#runkeydown",
    "class/js/object.js~ConvertContainer.html#instance-method-runKeydown",
    "js/object.js~ConvertContainer#runKeydown",
    "method"
  ],
  [
    "js/object.js~convertcontainer#shiftdown",
    "class/js/object.js~ConvertContainer.html#instance-method-shiftDown",
    "js/object.js~ConvertContainer#shiftDown",
    "method"
  ],
  [
    "js/object.js~convertcontainer#shiftup",
    "class/js/object.js~ConvertContainer.html#instance-method-shiftUp",
    "js/object.js~ConvertContainer#shiftUp",
    "method"
  ],
  [
    "js/object.js~convertcontainer#show",
    "class/js/object.js~ConvertContainer.html#instance-method-show",
    "js/object.js~ConvertContainer#show",
    "method"
  ],
  [
    "js/object.js~convertcontainer#views",
    "class/js/object.js~ConvertContainer.html#instance-method-views",
    "js/object.js~ConvertContainer#views",
    "method"
  ],
  [
    "js/object.js~convertview#active",
    "class/js/object.js~ConvertView.html#instance-method-active",
    "js/object.js~ConvertView#active",
    "method"
  ],
  [
    "js/object.js~convertview#after",
    "class/js/object.js~ConvertView.html#instance-method-after",
    "js/object.js~ConvertView#after",
    "method"
  ],
  [
    "js/object.js~convertview#append",
    "class/js/object.js~ConvertView.html#instance-method-append",
    "js/object.js~ConvertView#append",
    "method"
  ],
  [
    "js/object.js~convertview#before",
    "class/js/object.js~ConvertView.html#instance-method-before",
    "js/object.js~ConvertView#before",
    "method"
  ],
  [
    "js/object.js~convertview#constructor",
    "class/js/object.js~ConvertView.html#instance-constructor-constructor",
    "js/object.js~ConvertView#constructor",
    "method"
  ],
  [
    "js/object.js~convertview#container",
    "class/js/object.js~ConvertView.html#instance-method-container",
    "js/object.js~ConvertView#container",
    "method"
  ],
  [
    "js/object.js~convertview#getselect",
    "class/js/object.js~ConvertView.html#instance-method-getSelect",
    "js/object.js~ConvertView#getSelect",
    "method"
  ],
  [
    "js/object.js~convertview#hiragana",
    "class/js/object.js~ConvertView.html#instance-method-hiragana",
    "js/object.js~ConvertView#hiragana",
    "method"
  ],
  [
    "js/object.js~convertview#isactive",
    "class/js/object.js~ConvertView.html#instance-method-isActive",
    "js/object.js~ConvertView#isActive",
    "method"
  ],
  [
    "js/object.js~convertview#kanalength",
    "class/js/object.js~ConvertView.html#instance-method-kanaLength",
    "js/object.js~ConvertView#kanaLength",
    "method"
  ],
  [
    "js/object.js~convertview#phrasenum",
    "class/js/object.js~ConvertView.html#instance-method-phraseNum",
    "js/object.js~ConvertView#phraseNum",
    "method"
  ],
  [
    "js/object.js~convertview#remove",
    "class/js/object.js~ConvertView.html#instance-method-remove",
    "js/object.js~ConvertView#remove",
    "method"
  ],
  [
    "js/object.js~convertview#replace",
    "class/js/object.js~ConvertView.html#instance-method-replace",
    "js/object.js~ConvertView#replace",
    "method"
  ],
  [
    "js/object.js~convertview#rows",
    "class/js/object.js~ConvertView.html#instance-method-rows",
    "js/object.js~ConvertView#rows",
    "method"
  ],
  [
    "js/object.js~convertview#select",
    "class/js/object.js~ConvertView.html#instance-method-select",
    "js/object.js~ConvertView#select",
    "method"
  ],
  [
    "js/object.js~convertview#selectleft",
    "class/js/object.js~ConvertView.html#instance-method-selectLeft",
    "js/object.js~ConvertView#selectLeft",
    "method"
  ],
  [
    "js/object.js~convertview#selectright",
    "class/js/object.js~ConvertView.html#instance-method-selectRight",
    "js/object.js~ConvertView#selectRight",
    "method"
  ],
  [
    "js/object.js~convertview#tokatakana",
    "class/js/object.js~ConvertView.html#instance-method-toKatakana",
    "js/object.js~ConvertView#toKatakana",
    "method"
  ],
  [
    "js/object.js~cursor#addcursor",
    "class/js/object.js~Cursor.html#instance-method-addCursor",
    "js/object.js~Cursor#addCursor",
    "method"
  ],
  [
    "js/object.js~cursor#backspace",
    "class/js/object.js~Cursor.html#instance-method-backSpace",
    "js/object.js~Cursor#backSpace",
    "method"
  ],
  [
    "js/object.js~cursor#constructor",
    "class/js/object.js~Cursor.html#instance-constructor-constructor",
    "js/object.js~Cursor#constructor",
    "method"
  ],
  [
    "js/object.js~cursor#createcursorline",
    "class/js/object.js~Cursor.html#instance-method-createCursorLine",
    "js/object.js~Cursor#createCursorLine",
    "method"
  ],
  [
    "js/object.js~cursor#currentcharpos",
    "class/js/object.js~Cursor.html#instance-method-currentCharPos",
    "js/object.js~Cursor#currentCharPos",
    "method"
  ],
  [
    "js/object.js~cursor#currentpage",
    "class/js/object.js~Cursor.html#instance-method-currentPage",
    "js/object.js~Cursor#currentPage",
    "method"
  ],
  [
    "js/object.js~cursor#currentrowpos",
    "class/js/object.js~Cursor.html#instance-method-currentRowPos",
    "js/object.js~Cursor#currentRowPos",
    "method"
  ],
  [
    "js/object.js~cursor#cursorlineelem",
    "class/js/object.js~Cursor.html#instance-method-cursorLineElem",
    "js/object.js~Cursor#cursorLineElem",
    "method"
  ],
  [
    "js/object.js~cursor#extendselection",
    "class/js/object.js~Cursor.html#instance-method-extendSelection",
    "js/object.js~Cursor#extendSelection",
    "method"
  ],
  [
    "js/object.js~cursor#getchar",
    "class/js/object.js~Cursor.html#instance-method-getChar",
    "js/object.js~Cursor#getChar",
    "method"
  ],
  [
    "js/object.js~cursor#getparagraph",
    "class/js/object.js~Cursor.html#instance-method-getParagraph",
    "js/object.js~Cursor#getParagraph",
    "method"
  ],
  [
    "js/object.js~cursor#getposmemory",
    "class/js/object.js~Cursor.html#instance-method-getPosMemory",
    "js/object.js~Cursor#getPosMemory",
    "method"
  ],
  [
    "js/object.js~cursor#getrow",
    "class/js/object.js~Cursor.html#instance-method-getRow",
    "js/object.js~Cursor#getRow",
    "method"
  ],
  [
    "js/object.js~cursor#init",
    "class/js/object.js~Cursor.html#instance-method-init",
    "js/object.js~Cursor#init",
    "method"
  ],
  [
    "js/object.js~cursor#insert",
    "class/js/object.js~Cursor.html#instance-method-insert",
    "js/object.js~Cursor#insert",
    "method"
  ],
  [
    "js/object.js~cursor#jumppage",
    "class/js/object.js~Cursor.html#instance-method-jumpPage",
    "js/object.js~Cursor#jumpPage",
    "method"
  ],
  [
    "js/object.js~cursor#jumprow",
    "class/js/object.js~Cursor.html#instance-method-jumpRow",
    "js/object.js~Cursor#jumpRow",
    "method"
  ],
  [
    "js/object.js~cursor#linebreak",
    "class/js/object.js~Cursor.html#instance-method-lineBreak",
    "js/object.js~Cursor#lineBreak",
    "method"
  ],
  [
    "js/object.js~cursor#moveleft",
    "class/js/object.js~Cursor.html#instance-method-moveLeft",
    "js/object.js~Cursor#moveLeft",
    "method"
  ],
  [
    "js/object.js~cursor#movenext",
    "class/js/object.js~Cursor.html#instance-method-moveNext",
    "js/object.js~Cursor#moveNext",
    "method"
  ],
  [
    "js/object.js~cursor#moveprev",
    "class/js/object.js~Cursor.html#instance-method-movePrev",
    "js/object.js~Cursor#movePrev",
    "method"
  ],
  [
    "js/object.js~cursor#moveright",
    "class/js/object.js~Cursor.html#instance-method-moveRight",
    "js/object.js~Cursor#moveRight",
    "method"
  ],
  [
    "js/object.js~cursor#moverow",
    "class/js/object.js~Cursor.html#instance-method-moveRow",
    "js/object.js~Cursor#moveRow",
    "method"
  ],
  [
    "js/object.js~cursor#nextsearch",
    "class/js/object.js~Cursor.html#instance-method-nextSearch",
    "js/object.js~Cursor#nextSearch",
    "method"
  ],
  [
    "js/object.js~cursor#prevsearch",
    "class/js/object.js~Cursor.html#instance-method-prevSearch",
    "js/object.js~Cursor#prevSearch",
    "method"
  ],
  [
    "js/object.js~cursor#rowlenonpage",
    "class/js/object.js~Cursor.html#instance-method-rowLenOnPage",
    "js/object.js~Cursor#rowLenOnPage",
    "method"
  ],
  [
    "js/object.js~cursor#sentencecontainer",
    "class/js/object.js~Cursor.html#instance-method-sentenceContainer",
    "js/object.js~Cursor#sentenceContainer",
    "method"
  ],
  [
    "js/object.js~cursor#setposmemory",
    "class/js/object.js~Cursor.html#instance-method-setPosMemory",
    "js/object.js~Cursor#setPosMemory",
    "method"
  ],
  [
    "js/object.js~cursor#strlenofrow",
    "class/js/object.js~Cursor.html#instance-method-strLenOfRow",
    "js/object.js~Cursor#strLenOfRow",
    "method"
  ],
  [
    "js/object.js~directory#append",
    "class/js/object.js~Directory.html#instance-method-append",
    "js/object.js~Directory#append",
    "method"
  ],
  [
    "js/object.js~directory#appendelem",
    "class/js/object.js~Directory.html#instance-method-appendElem",
    "js/object.js~Directory#appendElem",
    "method"
  ],
  [
    "js/object.js~directory#constructor",
    "class/js/object.js~Directory.html#instance-constructor-constructor",
    "js/object.js~Directory#constructor",
    "method"
  ],
  [
    "js/object.js~directory#contains",
    "class/js/object.js~Directory.html#instance-method-contains",
    "js/object.js~Directory#contains",
    "method"
  ],
  [
    "js/object.js~directory#delete",
    "class/js/object.js~Directory.html#instance-method-delete",
    "js/object.js~Directory#delete",
    "method"
  ],
  [
    "js/object.js~directory#filelist",
    "class/js/object.js~Directory.html#instance-method-fileList",
    "js/object.js~Directory#fileList",
    "method"
  ],
  [
    "js/object.js~directory#findnextfile",
    "class/js/object.js~Directory.html#instance-method-findNextFile",
    "js/object.js~Directory#findNextFile",
    "method"
  ],
  [
    "js/object.js~directory#id",
    "class/js/object.js~Directory.html#instance-method-id",
    "js/object.js~Directory#id",
    "method"
  ],
  [
    "js/object.js~directory#innerlist",
    "class/js/object.js~Directory.html#instance-method-innerList",
    "js/object.js~Directory#innerList",
    "method"
  ],
  [
    "js/object.js~directory#isdirectory",
    "class/js/object.js~Directory.html#instance-method-isDirectory",
    "js/object.js~Directory#isDirectory",
    "method"
  ],
  [
    "js/object.js~directory#isfile",
    "class/js/object.js~Directory.html#instance-method-isFile",
    "js/object.js~Directory#isFile",
    "method"
  ],
  [
    "js/object.js~directory#isroot",
    "class/js/object.js~Directory.html#instance-method-isRoot",
    "js/object.js~Directory#isRoot",
    "method"
  ],
  [
    "js/object.js~directory#link",
    "class/js/object.js~Directory.html#instance-method-link",
    "js/object.js~Directory#link",
    "method"
  ],
  [
    "js/object.js~directory#name",
    "class/js/object.js~Directory.html#instance-method-name",
    "js/object.js~Directory#name",
    "method"
  ],
  [
    "js/object.js~eol#appended",
    "class/js/object.js~EOL.html#instance-method-appended",
    "js/object.js~EOL#appended",
    "method"
  ],
  [
    "js/object.js~eol#constructor",
    "class/js/object.js~EOL.html#instance-constructor-constructor",
    "js/object.js~EOL#constructor",
    "method"
  ],
  [
    "js/object.js~eol#index",
    "class/js/object.js~EOL.html#instance-method-index",
    "js/object.js~EOL#index",
    "method"
  ],
  [
    "js/object.js~eol#iseol",
    "class/js/object.js~EOL.html#instance-method-isEOL",
    "js/object.js~EOL#isEOL",
    "method"
  ],
  [
    "js/object.js~file#addclickeventlistener",
    "class/js/object.js~File.html#instance-method-addClickEventListener",
    "js/object.js~File#addClickEventListener",
    "method"
  ],
  [
    "js/object.js~file#constructor",
    "class/js/object.js~File.html#instance-constructor-constructor",
    "js/object.js~File#constructor",
    "method"
  ],
  [
    "js/object.js~file#delete",
    "class/js/object.js~File.html#instance-method-delete",
    "js/object.js~File#delete",
    "method"
  ],
  [
    "js/object.js~file#filelist",
    "class/js/object.js~File.html#instance-method-fileList",
    "js/object.js~File#fileList",
    "method"
  ],
  [
    "js/object.js~file#id",
    "class/js/object.js~File.html#instance-method-id",
    "js/object.js~File#id",
    "method"
  ],
  [
    "js/object.js~file#isclose",
    "class/js/object.js~File.html#instance-method-isClose",
    "js/object.js~File#isClose",
    "method"
  ],
  [
    "js/object.js~file#isdirectory",
    "class/js/object.js~File.html#instance-method-isDirectory",
    "js/object.js~File#isDirectory",
    "method"
  ],
  [
    "js/object.js~file#isfile",
    "class/js/object.js~File.html#instance-method-isFile",
    "js/object.js~File#isFile",
    "method"
  ],
  [
    "js/object.js~file#isfirstfile",
    "class/js/object.js~File.html#instance-method-isFirstFile",
    "js/object.js~File#isFirstFile",
    "method"
  ],
  [
    "js/object.js~file#islastfile",
    "class/js/object.js~File.html#instance-method-isLastFile",
    "js/object.js~File#isLastFile",
    "method"
  ],
  [
    "js/object.js~file#isopen",
    "class/js/object.js~File.html#instance-method-isOpen",
    "js/object.js~File#isOpen",
    "method"
  ],
  [
    "js/object.js~file#isroot",
    "class/js/object.js~File.html#instance-method-isRoot",
    "js/object.js~File#isRoot",
    "method"
  ],
  [
    "js/object.js~file#link",
    "class/js/object.js~File.html#instance-method-link",
    "js/object.js~File#link",
    "method"
  ],
  [
    "js/object.js~file#move",
    "class/js/object.js~File.html#instance-method-move",
    "js/object.js~File#move",
    "method"
  ],
  [
    "js/object.js~file#name",
    "class/js/object.js~File.html#instance-method-name",
    "js/object.js~File#name",
    "method"
  ],
  [
    "js/object.js~file#nextfile",
    "class/js/object.js~File.html#instance-method-nextFile",
    "js/object.js~File#nextFile",
    "method"
  ],
  [
    "js/object.js~file#open",
    "class/js/object.js~File.html#instance-method-open",
    "js/object.js~File#open",
    "method"
  ],
  [
    "js/object.js~file#prevfile",
    "class/js/object.js~File.html#instance-method-prevFile",
    "js/object.js~File#prevFile",
    "method"
  ],
  [
    "js/object.js~file#removeclickeventlistener",
    "class/js/object.js~File.html#instance-method-removeClickEventListener",
    "js/object.js~File#removeClickEventListener",
    "method"
  ],
  [
    "js/object.js~file#runclick",
    "class/js/object.js~File.html#instance-method-runClick",
    "js/object.js~File#runClick",
    "method"
  ],
  [
    "js/object.js~filelist#$modal",
    "class/js/object.js~FileList.html#instance-method-$modal",
    "js/object.js~FileList#$modal",
    "method"
  ],
  [
    "js/object.js~filelist#addeventlisteneroninput",
    "class/js/object.js~FileList.html#instance-method-addEventListenerOnInput",
    "js/object.js~FileList#addEventListenerOnInput",
    "method"
  ],
  [
    "js/object.js~filelist#append",
    "class/js/object.js~FileList.html#instance-method-append",
    "js/object.js~FileList#append",
    "method"
  ],
  [
    "js/object.js~filelist#appendelem",
    "class/js/object.js~FileList.html#instance-method-appendElem",
    "js/object.js~FileList#appendElem",
    "method"
  ],
  [
    "js/object.js~filelist#chainfile",
    "class/js/object.js~FileList.html#instance-method-chainFile",
    "js/object.js~FileList#chainFile",
    "method"
  ],
  [
    "js/object.js~filelist#constructor",
    "class/js/object.js~FileList.html#instance-constructor-constructor",
    "js/object.js~FileList#constructor",
    "method"
  ],
  [
    "js/object.js~filelist#currentfile",
    "class/js/object.js~FileList.html#instance-method-currentFile",
    "js/object.js~FileList#currentFile",
    "method"
  ],
  [
    "js/object.js~filelist#deletedirectory",
    "class/js/object.js~FileList.html#instance-method-deleteDirectory",
    "js/object.js~FileList#deleteDirectory",
    "method"
  ],
  [
    "js/object.js~filelist#deletefile",
    "class/js/object.js~FileList.html#instance-method-deleteFile",
    "js/object.js~FileList#deleteFile",
    "method"
  ],
  [
    "js/object.js~filelist#each",
    "class/js/object.js~FileList.html#instance-method-each",
    "js/object.js~FileList#each",
    "method"
  ],
  [
    "js/object.js~filelist#emptyelem",
    "class/js/object.js~FileList.html#instance-method-emptyElem",
    "js/object.js~FileList#emptyElem",
    "method"
  ],
  [
    "js/object.js~filelist#filter",
    "class/js/object.js~FileList.html#instance-method-filter",
    "js/object.js~FileList#filter",
    "method"
  ],
  [
    "js/object.js~filelist#filterinputelem",
    "class/js/object.js~FileList.html#instance-method-filterInputElem",
    "js/object.js~FileList#filterInputElem",
    "method"
  ],
  [
    "js/object.js~filelist#finddirectory",
    "class/js/object.js~FileList.html#instance-method-findDirectory",
    "js/object.js~FileList#findDirectory",
    "method"
  ],
  [
    "js/object.js~filelist#findfile",
    "class/js/object.js~FileList.html#instance-method-findFile",
    "js/object.js~FileList#findFile",
    "method"
  ],
  [
    "js/object.js~filelist#findnextfile",
    "class/js/object.js~FileList.html#instance-method-findNextFile",
    "js/object.js~FileList#findNextFile",
    "method"
  ],
  [
    "js/object.js~filelist#firstfile",
    "class/js/object.js~FileList.html#instance-method-firstFile",
    "js/object.js~FileList#firstFile",
    "method"
  ],
  [
    "js/object.js~filelist#hasfile",
    "class/js/object.js~FileList.html#instance-method-hasFile",
    "js/object.js~FileList#hasFile",
    "method"
  ],
  [
    "js/object.js~filelist#hidemodal",
    "class/js/object.js~FileList.html#instance-method-hideModal",
    "js/object.js~FileList#hideModal",
    "method"
  ],
  [
    "js/object.js~filelist#init",
    "class/js/object.js~FileList.html#instance-method-init",
    "js/object.js~FileList#init",
    "method"
  ],
  [
    "js/object.js~filelist#isdirectory",
    "class/js/object.js~FileList.html#instance-method-isDirectory",
    "js/object.js~FileList#isDirectory",
    "method"
  ],
  [
    "js/object.js~filelist#isfile",
    "class/js/object.js~FileList.html#instance-method-isFile",
    "js/object.js~FileList#isFile",
    "method"
  ],
  [
    "js/object.js~filelist#isopen",
    "class/js/object.js~FileList.html#instance-method-isOpen",
    "js/object.js~FileList#isOpen",
    "method"
  ],
  [
    "js/object.js~filelist#isroot",
    "class/js/object.js~FileList.html#instance-method-isRoot",
    "js/object.js~FileList#isRoot",
    "method"
  ],
  [
    "js/object.js~filelist#lastfile",
    "class/js/object.js~FileList.html#instance-method-lastFile",
    "js/object.js~FileList#lastFile",
    "method"
  ],
  [
    "js/object.js~filelist#mkdir",
    "class/js/object.js~FileList.html#instance-method-mkdir",
    "js/object.js~FileList#mkdir",
    "method"
  ],
  [
    "js/object.js~filelist#movefile",
    "class/js/object.js~FileList.html#instance-method-moveFile",
    "js/object.js~FileList#moveFile",
    "method"
  ],
  [
    "js/object.js~filelist#onkeyuponinput",
    "class/js/object.js~FileList.html#instance-method-onKeyupOnInput",
    "js/object.js~FileList#onKeyupOnInput",
    "method"
  ],
  [
    "js/object.js~filelist#opennextfile",
    "class/js/object.js~FileList.html#instance-method-openNextFile",
    "js/object.js~FileList#openNextFile",
    "method"
  ],
  [
    "js/object.js~filelist#openprevfile",
    "class/js/object.js~FileList.html#instance-method-openPrevFile",
    "js/object.js~FileList#openPrevFile",
    "method"
  ],
  [
    "js/object.js~filelist#read",
    "class/js/object.js~FileList.html#instance-method-read",
    "js/object.js~FileList#read",
    "method"
  ],
  [
    "js/object.js~filelist#resetlist",
    "class/js/object.js~FileList.html#instance-method-resetList",
    "js/object.js~FileList#resetList",
    "method"
  ],
  [
    "js/object.js~filelist#sentencecontainer",
    "class/js/object.js~FileList.html#instance-method-sentenceContainer",
    "js/object.js~FileList#sentenceContainer",
    "method"
  ],
  [
    "js/object.js~filelist#showmodal",
    "class/js/object.js~FileList.html#instance-method-showModal",
    "js/object.js~FileList#showModal",
    "method"
  ],
  [
    "js/object.js~inputbuffer#addkeydowneventlistener",
    "class/js/object.js~InputBuffer.html#instance-method-addKeydownEventListener",
    "js/object.js~InputBuffer#addKeydownEventListener",
    "method"
  ],
  [
    "js/object.js~inputbuffer#constructor",
    "class/js/object.js~InputBuffer.html#instance-constructor-constructor",
    "js/object.js~InputBuffer#constructor",
    "method"
  ],
  [
    "js/object.js~inputbuffer#container",
    "class/js/object.js~InputBuffer.html#instance-method-container",
    "js/object.js~InputBuffer#container",
    "method"
  ],
  [
    "js/object.js~inputbuffer#convert",
    "class/js/object.js~InputBuffer.html#instance-method-convert",
    "js/object.js~InputBuffer#convert",
    "method"
  ],
  [
    "js/object.js~inputbuffer#convertcontainer",
    "class/js/object.js~InputBuffer.html#instance-method-convertContainer",
    "js/object.js~InputBuffer#convertContainer",
    "method"
  ],
  [
    "js/object.js~inputbuffer#cursor",
    "class/js/object.js~InputBuffer.html#instance-method-cursor",
    "js/object.js~InputBuffer#cursor",
    "method"
  ],
  [
    "js/object.js~inputbuffer#cursorchar",
    "class/js/object.js~InputBuffer.html#instance-method-cursorChar",
    "js/object.js~InputBuffer#cursorChar",
    "method"
  ],
  [
    "js/object.js~inputbuffer#cursorx",
    "class/js/object.js~InputBuffer.html#instance-method-cursorX",
    "js/object.js~InputBuffer#cursorX",
    "method"
  ],
  [
    "js/object.js~inputbuffer#cursory",
    "class/js/object.js~InputBuffer.html#instance-method-cursorY",
    "js/object.js~InputBuffer#cursorY",
    "method"
  ],
  [
    "js/object.js~inputbuffer#decreace",
    "class/js/object.js~InputBuffer.html#instance-method-decreace",
    "js/object.js~InputBuffer#decreace",
    "method"
  ],
  [
    "js/object.js~inputbuffer#empty",
    "class/js/object.js~InputBuffer.html#instance-method-empty",
    "js/object.js~InputBuffer#empty",
    "method"
  ],
  [
    "js/object.js~inputbuffer#height",
    "class/js/object.js~InputBuffer.html#instance-method-height",
    "js/object.js~InputBuffer#height",
    "method"
  ],
  [
    "js/object.js~inputbuffer#hide",
    "class/js/object.js~InputBuffer.html#instance-method-hide",
    "js/object.js~InputBuffer#hide",
    "method"
  ],
  [
    "js/object.js~inputbuffer#increace",
    "class/js/object.js~InputBuffer.html#instance-method-increace",
    "js/object.js~InputBuffer#increace",
    "method"
  ],
  [
    "js/object.js~inputbuffer#insertphrase",
    "class/js/object.js~InputBuffer.html#instance-method-insertPhrase",
    "js/object.js~InputBuffer#insertPhrase",
    "method"
  ],
  [
    "js/object.js~inputbuffer#insertphraseafter",
    "class/js/object.js~InputBuffer.html#instance-method-insertPhraseAfter",
    "js/object.js~InputBuffer#insertPhraseAfter",
    "method"
  ],
  [
    "js/object.js~inputbuffer#isdisplay",
    "class/js/object.js~InputBuffer.html#instance-method-isDisplay",
    "js/object.js~InputBuffer#isDisplay",
    "method"
  ],
  [
    "js/object.js~inputbuffer#move",
    "class/js/object.js~InputBuffer.html#instance-method-move",
    "js/object.js~InputBuffer#move",
    "method"
  ],
  [
    "js/object.js~inputbuffer#phrases",
    "class/js/object.js~InputBuffer.html#instance-method-phrases",
    "js/object.js~InputBuffer#phrases",
    "method"
  ],
  [
    "js/object.js~inputbuffer#print",
    "class/js/object.js~InputBuffer.html#instance-method-print",
    "js/object.js~InputBuffer#print",
    "method"
  ],
  [
    "js/object.js~inputbuffer#resize",
    "class/js/object.js~InputBuffer.html#instance-method-resize",
    "js/object.js~InputBuffer#resize",
    "method"
  ],
  [
    "js/object.js~inputbuffer#runkeydown",
    "class/js/object.js~InputBuffer.html#instance-method-runKeydown",
    "js/object.js~InputBuffer#runKeydown",
    "method"
  ],
  [
    "js/object.js~inputbuffer#select",
    "class/js/object.js~InputBuffer.html#instance-method-select",
    "js/object.js~InputBuffer#select",
    "method"
  ],
  [
    "js/object.js~inputbuffer#selectindex",
    "class/js/object.js~InputBuffer.html#instance-method-selectIndex",
    "js/object.js~InputBuffer#selectIndex",
    "method"
  ],
  [
    "js/object.js~inputbuffer#selectnext",
    "class/js/object.js~InputBuffer.html#instance-method-selectNext",
    "js/object.js~InputBuffer#selectNext",
    "method"
  ],
  [
    "js/object.js~inputbuffer#selectphrases",
    "class/js/object.js~InputBuffer.html#instance-method-selectPhrases",
    "js/object.js~InputBuffer#selectPhrases",
    "method"
  ],
  [
    "js/object.js~inputbuffer#selectprev",
    "class/js/object.js~InputBuffer.html#instance-method-selectPrev",
    "js/object.js~InputBuffer#selectPrev",
    "method"
  ],
  [
    "js/object.js~inputbuffer#setphrasenum",
    "class/js/object.js~InputBuffer.html#instance-method-setPhraseNum",
    "js/object.js~InputBuffer#setPhraseNum",
    "method"
  ],
  [
    "js/object.js~inputbuffer#show",
    "class/js/object.js~InputBuffer.html#instance-method-show",
    "js/object.js~InputBuffer#show",
    "method"
  ],
  [
    "js/object.js~inputbuffer#tokatakanaall",
    "class/js/object.js~InputBuffer.html#instance-method-toKatakanaAll",
    "js/object.js~InputBuffer#toKatakanaAll",
    "method"
  ],
  [
    "js/object.js~inputbuffer#trytransfer",
    "class/js/object.js~InputBuffer.html#instance-method-tryTransfer",
    "js/object.js~InputBuffer#tryTransfer",
    "method"
  ],
  [
    "js/object.js~inputbuffer#update",
    "class/js/object.js~InputBuffer.html#instance-method-update",
    "js/object.js~InputBuffer#update",
    "method"
  ],
  [
    "js/object.js~inputbuffer#width",
    "class/js/object.js~InputBuffer.html#instance-method-width",
    "js/object.js~InputBuffer#width",
    "method"
  ],
  [
    "js/object.js~inputchar#constructor",
    "class/js/object.js~InputChar.html#instance-constructor-constructor",
    "js/object.js~InputChar#constructor",
    "method"
  ],
  [
    "js/object.js~inputchar#isphrasenum",
    "class/js/object.js~InputChar.html#instance-method-isPhraseNum",
    "js/object.js~InputChar#isPhraseNum",
    "method"
  ],
  [
    "js/object.js~inputchar#isselect",
    "class/js/object.js~InputChar.html#instance-method-isSelect",
    "js/object.js~InputChar#isSelect",
    "method"
  ],
  [
    "js/object.js~inputchar#phrasenum",
    "class/js/object.js~InputChar.html#instance-method-phraseNum",
    "js/object.js~InputChar#phraseNum",
    "method"
  ],
  [
    "js/object.js~inputchar#removeselect",
    "class/js/object.js~InputChar.html#instance-method-removeSelect",
    "js/object.js~InputChar#removeSelect",
    "method"
  ],
  [
    "js/object.js~inputchar#select",
    "class/js/object.js~InputChar.html#instance-method-select",
    "js/object.js~InputChar#select",
    "method"
  ],
  [
    "js/object.js~menu#addalignclickevent",
    "class/js/object.js~Menu.html#instance-method-addAlignClickEvent",
    "js/object.js~Menu#addAlignClickEvent",
    "method"
  ],
  [
    "js/object.js~menu#addcolor",
    "class/js/object.js~Menu.html#instance-method-addColor",
    "js/object.js~Menu#addColor",
    "method"
  ],
  [
    "js/object.js~menu#addcolorselectclickevent",
    "class/js/object.js~Menu.html#instance-method-addColorSelectClickEvent",
    "js/object.js~Menu#addColorSelectClickEvent",
    "method"
  ],
  [
    "js/object.js~menu#addconfigueevent",
    "class/js/object.js~Menu.html#instance-method-addConfigueEvent",
    "js/object.js~Menu#addConfigueEvent",
    "method"
  ],
  [
    "js/object.js~menu#addeventlisteners",
    "class/js/object.js~Menu.html#instance-method-addEventListeners",
    "js/object.js~Menu#addEventListeners",
    "method"
  ],
  [
    "js/object.js~menu#addfontsizeevnet",
    "class/js/object.js~Menu.html#instance-method-addFontSizeEvnet",
    "js/object.js~Menu#addFontSizeEvnet",
    "method"
  ],
  [
    "js/object.js~menu#align",
    "class/js/object.js~Menu.html#instance-method-align",
    "js/object.js~Menu#align",
    "method"
  ],
  [
    "js/object.js~menu#bold",
    "class/js/object.js~Menu.html#instance-method-bold",
    "js/object.js~Menu#bold",
    "method"
  ],
  [
    "js/object.js~menu#boldbutton",
    "class/js/object.js~Menu.html#instance-method-boldButton",
    "js/object.js~Menu#boldButton",
    "method"
  ],
  [
    "js/object.js~menu#chardecolations",
    "class/js/object.js~Menu.html#instance-method-charDecolations",
    "js/object.js~Menu#charDecolations",
    "method"
  ],
  [
    "js/object.js~menu#colorbutton",
    "class/js/object.js~Menu.html#instance-method-colorButton",
    "js/object.js~Menu#colorButton",
    "method"
  ],
  [
    "js/object.js~menu#confrowlenelem",
    "class/js/object.js~Menu.html#instance-method-confRowLenElem",
    "js/object.js~Menu#confRowLenElem",
    "method"
  ],
  [
    "js/object.js~menu#confstrlenelem",
    "class/js/object.js~Menu.html#instance-method-confStrLenElem",
    "js/object.js~Menu#confStrLenElem",
    "method"
  ],
  [
    "js/object.js~menu#configuedata",
    "class/js/object.js~Menu.html#instance-method-configueData",
    "js/object.js~Menu#configueData",
    "method"
  ],
  [
    "js/object.js~menu#constructor",
    "class/js/object.js~Menu.html#instance-constructor-constructor",
    "js/object.js~Menu#constructor",
    "method"
  ],
  [
    "js/object.js~menu#fontsize",
    "class/js/object.js~Menu.html#instance-method-fontSize",
    "js/object.js~Menu#fontSize",
    "method"
  ],
  [
    "js/object.js~menu#fontsizeinput",
    "class/js/object.js~Menu.html#instance-method-fontSizeInput",
    "js/object.js~Menu#fontSizeInput",
    "method"
  ],
  [
    "js/object.js~menu#italic",
    "class/js/object.js~Menu.html#instance-method-italic",
    "js/object.js~Menu#italic",
    "method"
  ],
  [
    "js/object.js~menu#italicbutton",
    "class/js/object.js~Menu.html#instance-method-italicButton",
    "js/object.js~Menu#italicButton",
    "method"
  ],
  [
    "js/object.js~menu#sentencecontainer",
    "class/js/object.js~Menu.html#instance-method-sentenceContainer",
    "js/object.js~Menu#sentenceContainer",
    "method"
  ],
  [
    "js/object.js~paragraph#after",
    "class/js/object.js~Paragraph.html#instance-method-after",
    "js/object.js~Paragraph#after",
    "method"
  ],
  [
    "js/object.js~paragraph#align",
    "class/js/object.js~Paragraph.html#instance-method-align",
    "js/object.js~Paragraph#align",
    "method"
  ],
  [
    "js/object.js~paragraph#append",
    "class/js/object.js~Paragraph.html#instance-method-append",
    "js/object.js~Paragraph#append",
    "method"
  ],
  [
    "js/object.js~paragraph#checkkinsoku",
    "class/js/object.js~Paragraph.html#instance-method-checkKinsoku",
    "js/object.js~Paragraph#checkKinsoku",
    "method"
  ],
  [
    "js/object.js~paragraph#classarray",
    "class/js/object.js~Paragraph.html#instance-method-classArray",
    "js/object.js~Paragraph#classArray",
    "method"
  ],
  [
    "js/object.js~paragraph#constructor",
    "class/js/object.js~Paragraph.html#instance-constructor-constructor",
    "js/object.js~Paragraph#constructor",
    "method"
  ],
  [
    "js/object.js~paragraph#container",
    "class/js/object.js~Paragraph.html#instance-method-container",
    "js/object.js~Paragraph#container",
    "method"
  ],
  [
    "js/object.js~paragraph#contains",
    "class/js/object.js~Paragraph.html#instance-method-contains",
    "js/object.js~Paragraph#contains",
    "method"
  ],
  [
    "js/object.js~paragraph#cordinate",
    "class/js/object.js~Paragraph.html#instance-method-cordinate",
    "js/object.js~Paragraph#cordinate",
    "method"
  ],
  [
    "js/object.js~paragraph#countchar",
    "class/js/object.js~Paragraph.html#instance-method-countChar",
    "js/object.js~Paragraph#countChar",
    "method"
  ],
  [
    "js/object.js~paragraph#data",
    "class/js/object.js~Paragraph.html#instance-method-data",
    "js/object.js~Paragraph#data",
    "method"
  ],
  [
    "js/object.js~paragraph#delete",
    "class/js/object.js~Paragraph.html#instance-method-delete",
    "js/object.js~Paragraph#delete",
    "method"
  ],
  [
    "js/object.js~paragraph#deleterow",
    "class/js/object.js~Paragraph.html#instance-method-deleteRow",
    "js/object.js~Paragraph#deleteRow",
    "method"
  ],
  [
    "js/object.js~paragraph#display",
    "class/js/object.js~Paragraph.html#instance-method-display",
    "js/object.js~Paragraph#display",
    "method"
  ],
  [
    "js/object.js~paragraph#divide",
    "class/js/object.js~Paragraph.html#instance-method-divide",
    "js/object.js~Paragraph#divide",
    "method"
  ],
  [
    "js/object.js~paragraph#hascursor",
    "class/js/object.js~Paragraph.html#instance-method-hasCursor",
    "js/object.js~Paragraph#hasCursor",
    "method"
  ],
  [
    "js/object.js~paragraph#hasrow",
    "class/js/object.js~Paragraph.html#instance-method-hasRow",
    "js/object.js~Paragraph#hasRow",
    "method"
  ],
  [
    "js/object.js~paragraph#insertrow",
    "class/js/object.js~Paragraph.html#instance-method-insertRow",
    "js/object.js~Paragraph#insertRow",
    "method"
  ],
  [
    "js/object.js~paragraph#isempty",
    "class/js/object.js~Paragraph.html#instance-method-isEmpty",
    "js/object.js~Paragraph#isEmpty",
    "method"
  ],
  [
    "js/object.js~paragraph#pushrow",
    "class/js/object.js~Paragraph.html#instance-method-pushRow",
    "js/object.js~Paragraph#pushRow",
    "method"
  ],
  [
    "js/object.js~paragraph#remove",
    "class/js/object.js~Paragraph.html#instance-method-remove",
    "js/object.js~Paragraph#remove",
    "method"
  ],
  [
    "js/object.js~paragraph#removeclassfromallchar",
    "class/js/object.js~Paragraph.html#instance-method-removeClassFromAllChar",
    "js/object.js~Paragraph#removeClassFromAllChar",
    "method"
  ],
  [
    "js/object.js~paragraph#rows",
    "class/js/object.js~Paragraph.html#instance-method-rows",
    "js/object.js~Paragraph#rows",
    "method"
  ],
  [
    "js/object.js~paragraph#search",
    "class/js/object.js~Paragraph.html#instance-method-search",
    "js/object.js~Paragraph#search",
    "method"
  ],
  [
    "js/object.js~paragraph.createemptyparagraph",
    "class/js/object.js~Paragraph.html#static-method-createEmptyParagraph",
    "js/object.js~Paragraph.createEmptyParagraph",
    "method"
  ],
  [
    "js/object.js~row#eol",
    "class/js/object.js~Row.html#instance-method-EOL",
    "js/object.js~Row#EOL",
    "method"
  ],
  [
    "js/object.js~row#after",
    "class/js/object.js~Row.html#instance-method-after",
    "js/object.js~Row#after",
    "method"
  ],
  [
    "js/object.js~row#aftereach",
    "class/js/object.js~Row.html#instance-method-afterEach",
    "js/object.js~Row#afterEach",
    "method"
  ],
  [
    "js/object.js~row#append",
    "class/js/object.js~Row.html#instance-method-append",
    "js/object.js~Row#append",
    "method"
  ],
  [
    "js/object.js~row#before",
    "class/js/object.js~Row.html#instance-method-before",
    "js/object.js~Row#before",
    "method"
  ],
  [
    "js/object.js~row#bringchar",
    "class/js/object.js~Row.html#instance-method-bringChar",
    "js/object.js~Row#bringChar",
    "method"
  ],
  [
    "js/object.js~row#bringchars",
    "class/js/object.js~Row.html#instance-method-bringChars",
    "js/object.js~Row#bringChars",
    "method"
  ],
  [
    "js/object.js~row#charlen",
    "class/js/object.js~Row.html#instance-method-charLen",
    "js/object.js~Row#charLen",
    "method"
  ],
  [
    "js/object.js~row#chars",
    "class/js/object.js~Row.html#instance-method-chars",
    "js/object.js~Row#chars",
    "method"
  ],
  [
    "js/object.js~row#checkkinsoku",
    "class/js/object.js~Row.html#instance-method-checkKinsoku",
    "js/object.js~Row#checkKinsoku",
    "method"
  ],
  [
    "js/object.js~row#children",
    "class/js/object.js~Row.html#instance-method-children",
    "js/object.js~Row#children",
    "method"
  ],
  [
    "js/object.js~row#computedisplaycharpos",
    "class/js/object.js~Row.html#instance-method-computeDisplayCharPos",
    "js/object.js~Row#computeDisplayCharPos",
    "method"
  ],
  [
    "js/object.js~row#constructor",
    "class/js/object.js~Row.html#instance-constructor-constructor",
    "js/object.js~Row#constructor",
    "method"
  ],
  [
    "js/object.js~row#container",
    "class/js/object.js~Row.html#instance-method-container",
    "js/object.js~Row#container",
    "method"
  ],
  [
    "js/object.js~row#contains",
    "class/js/object.js~Row.html#instance-method-contains",
    "js/object.js~Row#contains",
    "method"
  ],
  [
    "js/object.js~row#cordinate",
    "class/js/object.js~Row.html#instance-method-cordinate",
    "js/object.js~Row#cordinate",
    "method"
  ],
  [
    "js/object.js~row#createplaincontent",
    "class/js/object.js~Row.html#instance-method-createPlainContent",
    "js/object.js~Row#createPlainContent",
    "method"
  ],
  [
    "js/object.js~row#cursorchar",
    "class/js/object.js~Row.html#instance-method-cursorChar",
    "js/object.js~Row#cursorChar",
    "method"
  ],
  [
    "js/object.js~row#data",
    "class/js/object.js~Row.html#instance-method-data",
    "js/object.js~Row#data",
    "method"
  ],
  [
    "js/object.js~row#delete",
    "class/js/object.js~Row.html#instance-method-delete",
    "js/object.js~Row#delete",
    "method"
  ],
  [
    "js/object.js~row#deletechar",
    "class/js/object.js~Row.html#instance-method-deleteChar",
    "js/object.js~Row#deleteChar",
    "method"
  ],
  [
    "js/object.js~row#display",
    "class/js/object.js~Row.html#instance-method-display",
    "js/object.js~Row#display",
    "method"
  ],
  [
    "js/object.js~row#empty",
    "class/js/object.js~Row.html#instance-method-empty",
    "js/object.js~Row#empty",
    "method"
  ],
  [
    "js/object.js~row#firstchild",
    "class/js/object.js~Row.html#instance-method-firstChild",
    "js/object.js~Row#firstChild",
    "method"
  ],
  [
    "js/object.js~row#firstdisplaycharpos",
    "class/js/object.js~Row.html#instance-method-firstDisplayCharPos",
    "js/object.js~Row#firstDisplayCharPos",
    "method"
  ],
  [
    "js/object.js~row#haschar",
    "class/js/object.js~Row.html#instance-method-hasChar",
    "js/object.js~Row#hasChar",
    "method"
  ],
  [
    "js/object.js~row#hascursor",
    "class/js/object.js~Row.html#instance-method-hasCursor",
    "js/object.js~Row#hasCursor",
    "method"
  ],
  [
    "js/object.js~row#height",
    "class/js/object.js~Row.html#instance-method-height",
    "js/object.js~Row#height",
    "method"
  ],
  [
    "js/object.js~row#insertchar",
    "class/js/object.js~Row.html#instance-method-insertChar",
    "js/object.js~Row#insertChar",
    "method"
  ],
  [
    "js/object.js~row#isdisplay",
    "class/js/object.js~Row.html#instance-method-isDisplay",
    "js/object.js~Row#isDisplay",
    "method"
  ],
  [
    "js/object.js~row#ispagebreak",
    "class/js/object.js~Row.html#instance-method-isPageBreak",
    "js/object.js~Row#isPageBreak",
    "method"
  ],
  [
    "js/object.js~row#ispagelast",
    "class/js/object.js~Row.html#instance-method-isPageLast",
    "js/object.js~Row#isPageLast",
    "method"
  ],
  [
    "js/object.js~row#lastchar",
    "class/js/object.js~Row.html#instance-method-lastChar",
    "js/object.js~Row#lastChar",
    "method"
  ],
  [
    "js/object.js~row#lastchild",
    "class/js/object.js~Row.html#instance-method-lastChild",
    "js/object.js~Row#lastChild",
    "method"
  ],
  [
    "js/object.js~row#lastdisplaycharpos",
    "class/js/object.js~Row.html#instance-method-lastDisplayCharPos",
    "js/object.js~Row#lastDisplayCharPos",
    "method"
  ],
  [
    "js/object.js~row#maxfont",
    "class/js/object.js~Row.html#instance-method-maxFont",
    "js/object.js~Row#maxFont",
    "method"
  ],
  [
    "js/object.js~row#movelastbefore",
    "class/js/object.js~Row.html#instance-method-moveLastBefore",
    "js/object.js~Row#moveLastBefore",
    "method"
  ],
  [
    "js/object.js~row#paragraph",
    "class/js/object.js~Row.html#instance-method-paragraph",
    "js/object.js~Row#paragraph",
    "method"
  ],
  [
    "js/object.js~row#prepend",
    "class/js/object.js~Row.html#instance-method-prepend",
    "js/object.js~Row#prepend",
    "method"
  ],
  [
    "js/object.js~row#pushchar",
    "class/js/object.js~Row.html#instance-method-pushChar",
    "js/object.js~Row#pushChar",
    "method"
  ],
  [
    "js/object.js~row#remove",
    "class/js/object.js~Row.html#instance-method-remove",
    "js/object.js~Row#remove",
    "method"
  ],
  [
    "js/object.js~row#runclick",
    "class/js/object.js~Row.html#instance-method-runClick",
    "js/object.js~Row#runClick",
    "method"
  ],
  [
    "js/object.js~row#takechar",
    "class/js/object.js~Row.html#instance-method-takeChar",
    "js/object.js~Row#takeChar",
    "method"
  ],
  [
    "js/object.js~row#takechars",
    "class/js/object.js~Row.html#instance-method-takeChars",
    "js/object.js~Row#takeChars",
    "method"
  ],
  [
    "js/object.js~row#width",
    "class/js/object.js~Row.html#instance-method-width",
    "js/object.js~Row#width",
    "method"
  ],
  [
    "js/object.js~row.createemptyrow",
    "class/js/object.js~Row.html#static-method-createEmptyRow",
    "js/object.js~Row.createEmptyRow",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#adddisplay",
    "class/js/object.js~SentenceContainer.html#instance-method-addDisplay",
    "js/object.js~SentenceContainer#addDisplay",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#addfiletitleevent",
    "class/js/object.js~SentenceContainer.html#instance-method-addFileTitleEvent",
    "js/object.js~SentenceContainer#addFileTitleEvent",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#addkeydowneventlistener",
    "class/js/object.js~SentenceContainer.html#instance-method-addKeydownEventListener",
    "js/object.js~SentenceContainer#addKeydownEventListener",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#addselectevent",
    "class/js/object.js~SentenceContainer.html#instance-method-addSelectEvent",
    "js/object.js~SentenceContainer#addSelectEvent",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#append",
    "class/js/object.js~SentenceContainer.html#instance-method-append",
    "js/object.js~SentenceContainer#append",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#breakpage",
    "class/js/object.js~SentenceContainer.html#instance-method-breakPage",
    "js/object.js~SentenceContainer#breakPage",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#changedisplay",
    "class/js/object.js~SentenceContainer.html#instance-method-changeDisplay",
    "js/object.js~SentenceContainer#changeDisplay",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#checkkinsoku",
    "class/js/object.js~SentenceContainer.html#instance-method-checkKinsoku",
    "js/object.js~SentenceContainer#checkKinsoku",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#command",
    "class/js/object.js~SentenceContainer.html#instance-method-command",
    "js/object.js~SentenceContainer#command",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#constructor",
    "class/js/object.js~SentenceContainer.html#instance-constructor-constructor",
    "js/object.js~SentenceContainer#constructor",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#copyselecttext",
    "class/js/object.js~SentenceContainer.html#instance-method-copySelectText",
    "js/object.js~SentenceContainer#copySelectText",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#cordinate",
    "class/js/object.js~SentenceContainer.html#instance-method-cordinate",
    "js/object.js~SentenceContainer#cordinate",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#countchar",
    "class/js/object.js~SentenceContainer.html#instance-method-countChar",
    "js/object.js~SentenceContainer#countChar",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#countpage",
    "class/js/object.js~SentenceContainer.html#instance-method-countPage",
    "js/object.js~SentenceContainer#countPage",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#countrow",
    "class/js/object.js~SentenceContainer.html#instance-method-countRow",
    "js/object.js~SentenceContainer#countRow",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#cursor",
    "class/js/object.js~SentenceContainer.html#instance-method-cursor",
    "js/object.js~SentenceContainer#cursor",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#cursorchar",
    "class/js/object.js~SentenceContainer.html#instance-method-cursorChar",
    "js/object.js~SentenceContainer#cursorChar",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#cursorrow",
    "class/js/object.js~SentenceContainer.html#instance-method-cursorRow",
    "js/object.js~SentenceContainer#cursorRow",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#data",
    "class/js/object.js~SentenceContainer.html#instance-method-data",
    "js/object.js~SentenceContainer#data",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#deleteparagraph",
    "class/js/object.js~SentenceContainer.html#instance-method-deleteParagraph",
    "js/object.js~SentenceContainer#deleteParagraph",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#empty",
    "class/js/object.js~SentenceContainer.html#instance-method-empty",
    "js/object.js~SentenceContainer#empty",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#fileid",
    "class/js/object.js~SentenceContainer.html#instance-method-fileId",
    "js/object.js~SentenceContainer#fileId",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#filelist",
    "class/js/object.js~SentenceContainer.html#instance-method-fileList",
    "js/object.js~SentenceContainer#fileList",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#filename",
    "class/js/object.js~SentenceContainer.html#instance-method-filename",
    "js/object.js~SentenceContainer#filename",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#firstchar",
    "class/js/object.js~SentenceContainer.html#instance-method-firstChar",
    "js/object.js~SentenceContainer#firstChar",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#firstrow",
    "class/js/object.js~SentenceContainer.html#instance-method-firstRow",
    "js/object.js~SentenceContainer#firstRow",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#hasparagraph",
    "class/js/object.js~SentenceContainer.html#instance-method-hasParagraph",
    "js/object.js~SentenceContainer#hasParagraph",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#height",
    "class/js/object.js~SentenceContainer.html#instance-method-height",
    "js/object.js~SentenceContainer#height",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#init",
    "class/js/object.js~SentenceContainer.html#instance-method-init",
    "js/object.js~SentenceContainer#init",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#inputbuffer",
    "class/js/object.js~SentenceContainer.html#instance-method-inputBuffer",
    "js/object.js~SentenceContainer#inputBuffer",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#insertparagraph",
    "class/js/object.js~SentenceContainer.html#instance-method-insertParagraph",
    "js/object.js~SentenceContainer#insertParagraph",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#lastchar",
    "class/js/object.js~SentenceContainer.html#instance-method-lastChar",
    "js/object.js~SentenceContainer#lastChar",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#lasteol",
    "class/js/object.js~SentenceContainer.html#instance-method-lastEOL",
    "js/object.js~SentenceContainer#lastEOL",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#lastrow",
    "class/js/object.js~SentenceContainer.html#instance-method-lastRow",
    "js/object.js~SentenceContainer#lastRow",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#menu",
    "class/js/object.js~SentenceContainer.html#instance-method-menu",
    "js/object.js~SentenceContainer#menu",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#newfile",
    "class/js/object.js~SentenceContainer.html#instance-method-newFile",
    "js/object.js~SentenceContainer#newFile",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#onfocusinonsearchmode",
    "class/js/object.js~SentenceContainer.html#instance-method-onFocusinOnSearchMode",
    "js/object.js~SentenceContainer#onFocusinOnSearchMode",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#onfocusoutonsearchmode",
    "class/js/object.js~SentenceContainer.html#instance-method-onFocusoutOnSearchMode",
    "js/object.js~SentenceContainer#onFocusoutOnSearchMode",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#onkeyuponsearchmode",
    "class/js/object.js~SentenceContainer.html#instance-method-onKeyupOnSearchMode",
    "js/object.js~SentenceContainer#onKeyupOnSearchMode",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#pagerow",
    "class/js/object.js~SentenceContainer.html#instance-method-pageRow",
    "js/object.js~SentenceContainer#pageRow",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#paragraphs",
    "class/js/object.js~SentenceContainer.html#instance-method-paragraphs",
    "js/object.js~SentenceContainer#paragraphs",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#pastetext",
    "class/js/object.js~SentenceContainer.html#instance-method-pasteText",
    "js/object.js~SentenceContainer#pasteText",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#printinfo",
    "class/js/object.js~SentenceContainer.html#instance-method-printInfo",
    "js/object.js~SentenceContainer#printInfo",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#pushparagraph",
    "class/js/object.js~SentenceContainer.html#instance-method-pushParagraph",
    "js/object.js~SentenceContainer#pushParagraph",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#readfile",
    "class/js/object.js~SentenceContainer.html#instance-method-readFile",
    "js/object.js~SentenceContainer#readFile",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#removeclassfromallchar",
    "class/js/object.js~SentenceContainer.html#instance-method-removeClassFromAllChar",
    "js/object.js~SentenceContainer#removeClassFromAllChar",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#resetdisplay",
    "class/js/object.js~SentenceContainer.html#instance-method-resetDisplay",
    "js/object.js~SentenceContainer#resetDisplay",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#row",
    "class/js/object.js~SentenceContainer.html#instance-method-row",
    "js/object.js~SentenceContainer#row",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#rowlenonpage",
    "class/js/object.js~SentenceContainer.html#instance-method-rowLenOnPage",
    "js/object.js~SentenceContainer#rowLenOnPage",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#runkeydown",
    "class/js/object.js~SentenceContainer.html#instance-method-runKeydown",
    "js/object.js~SentenceContainer#runKeydown",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#runwheel",
    "class/js/object.js~SentenceContainer.html#instance-method-runWheel",
    "js/object.js~SentenceContainer#runWheel",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#saveasfile",
    "class/js/object.js~SentenceContainer.html#instance-method-saveAsFile",
    "js/object.js~SentenceContainer#saveAsFile",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#savefile",
    "class/js/object.js~SentenceContainer.html#instance-method-saveFile",
    "js/object.js~SentenceContainer#saveFile",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#saved",
    "class/js/object.js~SentenceContainer.html#instance-method-saved",
    "js/object.js~SentenceContainer#saved",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#search",
    "class/js/object.js~SentenceContainer.html#instance-method-search",
    "js/object.js~SentenceContainer#search",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#searchinputelem",
    "class/js/object.js~SentenceContainer.html#instance-method-searchInputElem",
    "js/object.js~SentenceContainer#searchInputElem",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#selectchars",
    "class/js/object.js~SentenceContainer.html#instance-method-selectChars",
    "js/object.js~SentenceContainer#selectChars",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#selecttext",
    "class/js/object.js~SentenceContainer.html#instance-method-selectText",
    "js/object.js~SentenceContainer#selectText",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#shiftleftdisplay",
    "class/js/object.js~SentenceContainer.html#instance-method-shiftLeftDisplay",
    "js/object.js~SentenceContainer#shiftLeftDisplay",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#shiftrightdisplay",
    "class/js/object.js~SentenceContainer.html#instance-method-shiftRightDisplay",
    "js/object.js~SentenceContainer#shiftRightDisplay",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#startsearchmode",
    "class/js/object.js~SentenceContainer.html#instance-method-startSearchMode",
    "js/object.js~SentenceContainer#startSearchMode",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#stopsearchmode",
    "class/js/object.js~SentenceContainer.html#instance-method-stopSearchMode",
    "js/object.js~SentenceContainer#stopSearchMode",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#strlenonrow",
    "class/js/object.js~SentenceContainer.html#instance-method-strLenOnRow",
    "js/object.js~SentenceContainer#strLenOnRow",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#titleelem",
    "class/js/object.js~SentenceContainer.html#instance-method-titleElem",
    "js/object.js~SentenceContainer#titleElem",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#useralert",
    "class/js/object.js~SentenceContainer.html#instance-method-userAlert",
    "js/object.js~SentenceContainer#userAlert",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#useralertelem",
    "class/js/object.js~SentenceContainer.html#instance-method-userAlertElem",
    "js/object.js~SentenceContainer#userAlertElem",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#userid",
    "class/js/object.js~SentenceContainer.html#instance-method-userId",
    "js/object.js~SentenceContainer#userId",
    "method"
  ],
  [
    "js/object.js~sentencecontainer#width",
    "class/js/object.js~SentenceContainer.html#instance-method-width",
    "js/object.js~SentenceContainer#width",
    "method"
  ]
]